### ISSUE TITLE
Conflict when using both javac and junit4 on wsl

### ISSUE THREAD

**Issue by amaberg** [repobee/repobee#382] opened 2019-11-16 13:39 UTC
It seems to be the same for any command

![Skärmklipp](https://user-images.githubusercontent.com/52538934/68994061-cdceb900-087e-11ea-98d8-d4030c3efc4d.JPG)

**Comment by slarse** [comment] 2019-11-16 16:08
Thank you for the bug report, this is due to a blatant oversight on my part. The problem is that two or more plugins (here, `javac` and `junit4`) try to add the same command line option to the same parser.

Plugins that add options to existing parsers should follow a naming convention, and RepoBee should enforce that convention (and put better error message when it is not followed, this error message is poor).

**Comment by slarse** [comment] 2019-11-26 14:02
This immediate clash has been resolved with repobee/repobee-junit4#54, now it's time to come up with a solution for how to make sure it doesn't happen again.

**Closed by slarse** 2019-11-26 14:02 UTC
Labels: bug, cli, plugin
